name: google_maps_flutter_web
description: Web platform implementation of google_maps_flutter
repository: https://github.com/flutter/plugins/tree/main/packages/google_maps_flutter/google_maps_flutter_web
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
version: 0.4.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: google_maps_flutter
    platforms:
      web:
        pluginClass: GoogleMapsPlugin
        fileName: google_maps_flutter_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_maps: ^6.1.0
  google_maps_flutter_platform_interface:
    git:
      url: https://github.com/Rexios80/plugins-1
      ref: c48ace56223931723609acb24c55a1a126513cef
      path: packages/google_maps_flutter/google_maps_flutter_platform_interface
      
  sanitize_html: ^2.0.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The example deliberately includes limited-use secrets.
false_secrets:
  - /example/web/index.html
